name: PHPUnit tests

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    phpunit:
        runs-on: ubuntu-24.04

        strategy:
            matrix:
                php-version: [ '8.1' ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, intl
                    coverage: yes

            -   name: php version
                run: php -v

            -   name: Install Composer dependencies
                run: composer install

            -   name: Run PHPUnit
                run: composer run tests-unit

            -   name: Run PHPUnit with code coverage
                run: composer run tests-coverage

            - name: Upload JUnit test results
              uses: actions/upload-artifact@v3
              with:
                name: junit-results
                path: ./tests-coverage/log/junit.xml

            - name: Upload coverage report
              uses: actions/upload-artifact@v3
              with:
                name: coverage-report
                path: ./tests-coverage/coverage/cobertura.xml
